name: Release Beta to Production
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Beta
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Production
        env:
          PROD_TOKEN: ${{ secrets.PROD_REPO_TOKEN }}
          TARGET_REPO: "szveresb/grit.hu"
        run: |
          set -euo pipefail
          git push --force \
            "https://x-access-token:${PROD_TOKEN}@github.com/${TARGET_REPO}.git" \
            "HEAD:refs/heads/main"
          
          echo "Successfully promoted Beta to Production."
